---

- name: Update dotfiles on target host
  hosts: all
  remote_user: jwlodek
  vars:
    user_home: "{{lookup('env', 'HOME')}}"
  tasks:
    - name: Retrieve dotfile repository on host
      git:
        clone: yes
        update: no
        recursive: no
        track_submodules: no
        force: yes
        dest: "{{user_home}}/dotfiles"
        repo: https://github.com/jwlodek/dotfiles
      environment:
        http_proxy: http://proxy:8888
        https_proxy: http://proxy:8888
   
    - name: Run deploy-dotfiles
      command:
        cmd: ./deploy-dotfiles.sh
        chdir: "{{user_home}}/dotfiles"
    
    - name: Cleanup user home
      command:
        cmd: rm -r dotfiles
        chdir: "{{user_home}}"
